name: CI
on:
  push:

jobs:
  test-job:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          MSBuild-version: '17'
      - run: MSBuild build
      - run: MSBuild test